### ISSUE TITLE
How can I use my own certificate

### ISSUE THREAD

**Issue by sayainchina** [jawj/IKEv2-setup#101]
Because I have my own certificate , Can I use it?

**Comment by jawj** [comment]
Yes — you'll want to drop your certificate files in `/etc/ipsec.d/certs/` and modify the section that starts with the line:

```
echo "--- Configuring RSA certificates ---"
```

**Comment by sayainchina** [comment]
Sorry,

> Yes — you'll want to drop your certificate files in `/etc/ipsec.d/certs/` and modify the section that starts with the line:
> 
> ```
> echo "--- Configuring RSA certificates ---"
> ```

Sorry,But I still did not understand，I try to "echo "--- Configuring RSA certificates ---""before bash the sh,but it didn't work,or you mean I need to modify the section manually?Thanks

**Comment by jawj** [comment]
Right. You probably want to cut most or all of that section, which gets a certificate from Let's Encrypt, because you've already obtained certificates and put them where they're expected.
