### ISSUE TITLE
iptables-persistent fucked up my server for a month...

### ISSUE THREAD

**Issue by sooxt98** [jawj/IKEv2-setup#103]
i have been spending time solving the iptables problem which always drop out my server network once a day.

**Comment by jawj** [comment]
I'm afraid this isn't a very helpful message. I do state in the README that the script is intended for use on a fresh server install that's not being used for anything else. If you have specific issues with the iptables rules, let me know.

**Comment by sooxt98** [comment]
@jawj  hi there, how to disable it? I just uninstalled it completely ;
