### ISSUE TITLE
Disconnect while installing — Broken pipe

### ISSUE THREAD

**Issue by krotish** [jawj/IKEv2-setup#105]
Hi, I've disconnected from server during install, looks like that is because firewall changes. 

see please output: 
```
--- Configuring VPN ---

net.ipv4.ip_forward = 1
net.ipv4.ip_no_pmtu_disc = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.all.accept_redirects = 0**client_loop: send disconnect: Broken pipe**
```

How can I make sure that server installed correctly and what's next steps? 

many thanks,
Ilya

**Comment by jawj** [comment]
Hmm, that's strange: I've never seen a disconnect during installation.

I guess you need to try to log back in via SSH (if the script got to the end, it should have created a new user to log in as and changed the SSH port to the one you entered). 

If you got the config email, you could also try to connect to the VPN.
