### ISSUE TITLE
Cannot connect to server after creating VPN

### ISSUE THREAD

**Issue by Ananjey** [jawj/IKEv2-setup#107]
Faced the following problem.
I connect to the server through an SSH connection that is provided by the service provider by default, I go to root with rights @sudo su@.
I execute the script of the script. As I understand it, the script disconnects the user from which it was launched and creates a new one by copying SSH keys. So, the entrance to the old user is already blocked.
But with a new user there will be a problem.
When logging in via the ssh client (I have putty), the following message is displayed: @Please login as the user “ubuntu” rather than the user “root”@
And all of you have lost contact with the server.
Of course I searched for a solution all day and found it. But everything must be done immediately without leaving the ssh session. Otherwise, it will not be possible to enter the server.

I had to edit .ssh/authorized_keys, to remove the following text:

no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="echo 'Please login as the user \"ubuntu\" rather than the user \"root\".';echo;sleep 10"
and keep the ssh-rsa and key that comes after it.

However, the command had copied the file to the new user, so I had to edit the file that was under /home/newuser/.ssh/authorized_keys rather than /root/.ssh/authorized_keys.

**Comment by Ananjey** [comment]
The problem is solved but I do not understand why it arose. And what did I do wrong?

**Comment by Ananjey** [comment]
And yet Windows 10 pro does not work VPN if I make a command
@ Set-VpnConnection -Name "130.61.247.35.sslip.io" -SplitTunneling $ True @ on the client. What could it be?
If I write @ Set-VpnConnection -Name "130.61.247.35.sslip.io" -SplitTunneling $ False @ everything will work.

**Comment by jawj** [comment]
On your first issue, you may have problems if your VPS provider does anything non-standard with the login setup. In that case, decline the script's offer to mess with this stuff.

On your second issue, Windows 10 VPN is a law unto itself, and it's probably worth asking questions on a Windows forum rather than here. Clarification of what "does not work" means would be a start, though ...
