### ISSUE TITLE
An unexpected error occurred.

### ISSUE THREAD

**Issue by MrBenFTW** [jawj/IKEv2-setup#108]
Hello, I am trying to make a IKEv2 VPN app for me and some friends to use. However, it refuses to connect, `An unexpected error occurred.`

This was on iOS 14, using this framework: [AVVPNService](https://github.com/AndreVasilev/AVVPNService)

To see if it was just the project or not I tried to manually add the VPN in iOS, this gave me the same `An unexpected error occurred.`

Since I was on iOS 14 which is currently in beta, I tried it on my Mac and also got the same error, yet when I use the mobile config generated, there is no error and I can connect just fine. 

It seems that the stock iOS/macOS cannot connect to this vpn without using the profile, do you know how I fix this?

**Comment by jawj** [comment]
Manually adding the VPN won't work as it doesn't allow secure ciphers. This is covered in the README. If the AVVPNService framework doesn't let you specify ciphers, it will have the same problem.

The workaround is probably to enable insecure ciphers in the Strongswan config. You can see some examples that should work at https://www.cl.cam.ac.uk/~mas90/resources/strongswan/#raw-ipsec.conf. But then, of course, your VPN won't be very secure.
