### ISSUE TITLE
iOS 

### ISSUE THREAD

**Issue by sherlockmac** [jawj/IKEv2-setup#11]
Stuck in "connecting"

**Comment by jawj** [comment]
OK, I kind of need more than that to go on. 

1. Are you able to see the logs on the server? 
Log in via SSH, then `sudo tail -f /var/log/syslog`, and try to connect.

2. Are you able to see logs on the client?
Download [Apple Configurator](https://itunes.apple.com/us/app/apple-configurator-2/id1037126344?mt=12) and run on your Mac, attach your iPhone, choose Console on the left, filter the output at top right to match `NetworkExtension`, and try to connect.

**Comment by pirate** [comment]
This may be related to #12, it would often stay stuck connecting for some time before eventually failing.  Try running this on your server and see if the issue persists:
```bash
sudo apt-get install -y strongswan-ikev2 libstrongswan-standard-plugins strongswan-libcharon libcharon-standard-plugins libcharon-extra-plugins
sudo ipsec restart
```

**Comment by jawj** [comment]
Timed out! I'll reopen is a reply is received.

**Comment by sherlockmac** [comment]
This is user log ... there's no log from server 

Jun  3 02:27:49 Alis-iPhone nesessionmanager(NetworkExtension)[1043] <Error>: Not hashing value with class __NSDate

Jun  3 02:27:49 Alis-iPhone nesessionmanager(NetworkExtension)[1043] <Notice>: NESMIKEv2VPNSession[private-uk.tk:A7D98324-753D-45FD-A4A3-5F2E19DAFA10]: Received a start command from Preferences[1109]

Jun  3 02:27:49 Alis-iPhone nesessionmanager(NetworkExtension)[1043] <Notice>: NESMIKEv2VPNSession[private-uk.tk:A7D98324-753D-45FD-A4A3-5F2E19DAFA10]: status changed to connecting

Jun  3 02:27:49 Alis-iPhone nesessionmanager(NetworkExtension)[1043] <Error>: Plugin com.apple.neplugin.IKEv2 does not have a bundle URL

Jun  3 02:27:49 Alis-iPhone kernel(Sandbox)[0] <Notice>: SandboxViolation: nesessionmanager(1043) deny(1) file-issue-extension target: /System/Library/Frameworks/NetworkExtension.framework/PluginIKEv2.vpnplugin class: com.apple.vpn-plugin

Jun  3 02:27:49 Alis-iPhone nesessionmanager(NetworkExtension)[1043] <Error>: sendInitCommand: failed to create a com.apple.vpn-plugin sandbox extension for /System/Library/Frameworks/NetworkExtension.framework/PluginIKEv2.vpnplugin

**Comment by pirate** [comment]
@sherlockmac It's a bug in iOS 10.3.2, I suspect Apple will probably fix it by 10.3.3 given the [number](https://forums.developer.apple.com/thread/75118) of [complaints](https://forums.developer.apple.com/thread/74939).

**Comment by jawj** [comment]
I think these iOS error messages are a red herring, because I see roughly the same logs on my iPhone (on 10.3.2) when I successfully connect:

    default 18:09:07.107305 +0100   nesessionmanager    NESMIKEv2VPNSession[vpn.mackerron.com:EE3EFFBA-65A9-4A15-95D0-E37EEFEC85E0]: Received a start command from Preferences[24074]
    default 18:09:07.111407 +0100   nesessionmanager    NESMIKEv2VPNSession[vpn.mackerron.com:EE3EFFBA-65A9-4A15-95D0-E37EEFEC85E0]: status changed to connecting
    error   18:09:07.114602 +0100   nesessionmanager    Plugin com.apple.neplugin.IKEv2 does not have a bundle URL
    default 18:09:07.131850 +0100   kernel  SandboxViolation: nesessionmanager(24718) deny(1) file-issue-extension target: /System/Library/Frameworks/NetworkExtension.framework/PluginIKEv2.vpnplugin class: com.apple.vpn-plugin
    error   18:09:07.132455 +0100   nesessionmanager    sendInitCommand: failed to create a com.apple.vpn-plugin sandbox extension for /System/Library/Frameworks/NetworkExtension.framework/PluginIKEv2.vpnplugin
    default 18:09:07.765848 +0100   nesessionmanager    NESMIKEv2VPNSession[vpn.mackerron.com:EE3EFFBA-65A9-4A15-95D0-E37EEFEC85E0]: status changed to connected

When you say there's no log from the server, do you mean you see no entries in `/var/log/syslog` when you try to connect? If so, it sounds like perhaps there's a more fundamental networking issue going on.

**Comment by sherlockmac** [comment]
Yes. No entries in `/var/log/syslog`.

I'm using iOS 10.3.3 beta 2 ... the issue shows only when I'm on cellular; with wifi, it's working fine. One more thing to note is if it's connected and I turn off the wifi it will continue working with cellular!

**Comment by jawj** [comment]
I suppose this could be either an iOS bug or some heavy-handed firewalling by your cellular provider?

We could probably rule out the latter if you were able to connect from your Mac or PC via tethering to your iPhone.

**Comment by sherlockmac** [comment]
It's not the network; I checked it by tethering the phone to my Mac and it worked without any issues. I suspect it's an iOS bug as @pirate mentioned.

Thanks for the quick follow-up.

✌🏼

**Comment by jawj** [comment]
Thanks for clarifying. I guess we just wait for a fix then.
