### ISSUE TITLE
It sucks dont use.

### ISSUE THREAD

**Issue by johncsuti** [jawj/IKEv2-setup#110]
broken absolutely broken.
Errors every time i try to run the script first /etc/ssh/sshd_config was not there when it was then it couldn't find openssh-server when it was already installed. JUST DONT USE THIS SCRIPT I HAVE NEVER SEEN ANYTHING MORE BROKEN IN MY LIFE..................

**Comment by jawj** [comment]
Rude and uninformative. I suspect you're not running this on Ubuntu Server 20.04.

**Comment by johncsuti** [comment]
i actually am but you just dont make good scrips
