### ISSUE TITLE
Unable to find pre-hook command /sbin/iptables in the PATH

### ISSUE THREAD

**Issue by bumansu** [jawj/IKEv2-setup#111]
I am trying to do a new vpn setup on ubuntu 20.04

unfortunately, I am getting following error.

--- Configuring RSA certificates ---

Unable to find pre-hook command /sbin/iptables in the PATH.
(PATH is /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin)

please help to fix it

**Comment by jawj** [comment]
Hmm, that's surprising. 

What server is this — e.g. is it a VPS somewhere?

What's the output if you type `which iptables`?

**Comment by bumansu** [comment]
I reinstalled Ubuntu and typed which iptables and shows nothing.

root@ubuntu:~# which iptables
root@ubuntu:~#

**Comment by bumansu** [comment]
`--- Configuration: VPN settings ---

./setup.sh: line 44: cho: command notfound
root@buburu:~# which iptables
root@buburu:~# `

**Comment by bumansu** [comment]
`--- Configuration: VPN settings ---

./setup.sh: line 44: cho: command notfound
root@ubuntu:~# which iptables
root@ubuntu:~# 
`

**Comment by bumansu** [comment]
I instead iptables 
`apt install iptables`.
Still same error.
`

which iptables
/usr/sbin/iptables

`

**Comment by jawj** [comment]
OK, and what if you now try to run `/sbin/iptables`? On my system, both `/sbin/iptables` and `/usr/sbin/iptables` point (via a ridiculous long chain of symlinks) to `/usr/sbin/xtables-legacy-multi`.

**Comment by bumansu** [comment]
`which /sbin/iptables`
shows nothing

**Comment by jawj** [comment]
So you could try replacing `/sbin/iptables` with `/usr/sbin/iptables` in the script, and see if it works then.

Otherwise, you might need to contact a Ubuntu forum (or your hosting provider) about it.

**Comment by bumansu** [comment]
thank you, it worked

**Comment by jawj** [comment]
Glad to hear it.
