### ISSUE TITLE
iOS not Signed 

### ISSUE THREAD

**Issue by Tayeh** [jawj/IKEv2-setup#116]
hi 
when installing the profile to an iOS device, the profile not Signed
![image](https://user-images.githubusercontent.com/9280478/101753083-56199080-3a76-11eb-8d6f-7c2b4162c8f2.png)

**Comment by jawj** [comment]
That's true, but not necessarily an error. It is possible to sign the profile with the Let's Encrypt certificate, but it doesn't really gain you anything, and the signing will expire with the certificate within 90 days.

**Comment by Tayeh** [comment]
how I can sign the profile

**Comment by Tayeh** [comment]
@jawj  it's urgent for me to sign the profile with the Let's Encrypt certificate because it's job requirement!

**Comment by Tayeh** [comment]
thanks @jawj 
I sign the profile with the Let's Encrypt certificate using openssl command  and it's work
