### ISSUE TITLE
can't make it work on digitalocean fresh droplet Ubuntu 20.04 Lts

### ISSUE THREAD

**Issue by CalmAndCoDe** [jawj/IKEv2-setup#117]
Hi, i have used your script to setup on digitalocean but i can't make it work, sometimes it works but sometimes it doesn't.
I don't know the actual reason but somehow i can't connect to the vps with android strongswan client app, it keeps showing 'Server is unreachable' although there is no any firewall in front of the vps i tried to define firewall rule and i allowed ingress udp traffic to both port 500 and 4500 but nothing changed, i also contacted digitalocean support to ask them if there are any restrictions but they said that try wipe your iptable rules and configure them again and i tried to copy the iptable rules from one of my vps servers which is working fine on digitalocean with the same script and still doesn't work.

**Comment by jawj** [comment]
Did you make it work?

**Comment by CalmAndCoDe** [comment]
@jawj Hi, yeah it wasn't error with the your script it was due the government firewall that blocked some of IP and it got fixed when i changed my vps public ip.
