### ISSUE TITLE
Connection issue from raspbian when having 2 active ssl certificates

### ISSUE THREAD

**Issue by sd-em** [jawj/IKEv2-setup#118]
Hi!
I use ubuntu 20.04.1 LTS as a server and raspbian linux machine as a client (used provided in this project vpn-ubuntu-client.sh script)

Everything worked fine with raspbian until Dec 17 when letsencrypt certificate has been automatically updated.
Now on the client side during execution of **ipsec up ikev2vpn** I see errors related with server certificate validation:
```
initiating IKE_SA ikev2vpn[3] to <server ip>
generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
sending packet: from <client ip>[500] to <server ip>[500] (296 bytes)
received packet: from <server ip>[500] to <client ip>[500] (304 bytes)
parsed IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(CHDLESS_SUP) N(MULT_AUTH) ]
selected proposal: IKE:AES_GCM_16_256/PRF_HMAC_SHA2_384/ECP_384
local host is behind NAT, sending keep alives
remote host is behind NAT
sending cert request for "O=Digital Signature Trust Co., CN=DST Root CA X3"
no IDi configured, fall back on IP address
establishing CHILD_SA ikev2vpn{3}
generating IKE_AUTH request 1 [ IDi N(INIT_CONTACT) CERTREQ IDr CPRQ(ADDR DNS) SA TSi TSr N(MOBIKE_SUP) N(ADD_4_ADDR) N(ADD_4_ADDR) N(MULT_AUTH) N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
sending packet: from <client ip>[4500] to <server ip>[4500] (274 bytes)
received packet: from <server ip>[4500] to <client ip>[4500] (1248 bytes)
parsed IKE_AUTH response 1 [ EF(1/2) ]
received fragment #1 of 2, waiting for complete IKE message
received packet: from <server ip>[4500] to <client ip>[4500] (1000 bytes)
parsed IKE_AUTH response 1 [ EF(2/2) ]
received fragment #2 of 2, reassembled fragmented IKE message (2183 bytes)
parsed IKE_AUTH response 1 [ IDr CERT AUTH EAP/REQ/ID ]
received end entity cert "CN=<my server domain>"
  using certificate "CN=<my server domain>"
no issuer certificate found for "CN=<my server domain>"
  issuer is "C=US, O=Let's Encrypt, CN=R3"
no trusted RSA public key found for '<my server domain>'
generating INFORMATIONAL request 2 [ N(AUTH_FAILED) ]
sending packet: from <client ip>[4500] to <server ip>[4500] (65 bytes)
establishing connection 'ikev2vpn' failed

```

First I ran **ipsec listcerts** on the server and there was 2 active certificates:
```
  subject:  "CN=<my server domain>"
  issuer:   "C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3"
  validity:  not before Oct 17 20:07:26 2020, ok
             not after  Jan 15 19:07:26 2021, ok (expires in 25 days)
...
  subject:  "CN=<my server domain>"
  issuer:   "C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3"
  validity:  not before Dec 17 02:18:26 2020, ok
             not after  Mar 17 02:18:26 2021, ok (expires in 86 days)
```

Next I got listing of /etc/letsencrypt/live/<my server domain> and saw that all symlinks were leading to most recent certificate in /etc/letsencrypt/archive folder. I then replaced that links with links to older certificate and vpn connection from raspbian started working. But I guess it will either stop working again after certificate update attempt this night or I'll have to update symlinks manually when current certificate expire. 
Is there anything I can do in order to get things working with the most recent certificate?
Taking into account that iOS and macOS clients work fine with the most recent cert I believe this issue could be addressed with some kind of configuration.

**Comment by jawj** [comment]
Sorry this response has come so late. 

The timing of your issue make it seem likely related to this change: https://community.letsencrypt.org/t/beginning-issuance-from-r3/139018

I wonder if you have all the required root certs installed on your Raspbian client?
