### ISSUE TITLE
How to uninstall script?

### ISSUE THREAD

**Issue by utap2001** [jawj/IKEv2-setup#119]
Hello, 
Do you have any method to uninstall this script?
or what setting needed to be deleted?

**Comment by TLWXPUser** [comment]
I'd also like instructions on how to revert the settings done by this script.

**Comment by jawj** [comment]
The project does say it's to work on a clean install, and not to use on a system you use for other things. I'm afraid I'm not willing to put the time into an uninstallation script or instructions. Basically you need to go through the installation script, deleting the files it creates, removing the parts of other files it changes or appends, reset your iptables rules, and so on.
