### ISSUE TITLE
How Connect Ikev2 To External Radius Server

### ISSUE THREAD

**Issue by raminmalekghasemi** [jawj/IKEv2-setup#121]
Hi Dears In this .sh code used Text File For username and password If i used Radius server for auth and acc 
Ho edit this .sh File ???

**Comment by jawj** [comment]
Hi there. Afraid I don't know. Suggest you check documentation for strongSwan and its plugins.

**Comment by raminmalekghasemi** [comment]
Please Share with name Of plugin that do this

**Comment by jawj** [comment]
Sorry: no idea.
