### ISSUE TITLE
Issue with IPtables Pre-Hook

### ISSUE THREAD

**Issue by johncsuti** [jawj/IKEv2-setup#122]
Trying to install the script on Ubuntu 20.04 when i get this error. Fresh install not sure whats wrong?
`--- Configuring firewall ---

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             state NEW recent: UPDATE seconds: 300 hit_count: 60 name: DEFAULT side: source mask: 255.255.255.255
           all  --  anywhere             anywhere             state NEW recent: SET name: DEFAULT side: source mask: 255.255.255.255
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere             state INVALID
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     udp  --  anywhere             anywhere             udp dpt:isakmp
ACCEPT     udp  --  anywhere             anywhere             udp dpt:ipsec-nat-t
DROP       all  --  anywhere             anywhere            

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  10.101.0.0/16        anywhere             policy match dir in pol ipsec proto esp
ACCEPT     all  --  anywhere             10.101.0.0/16        policy match dir out pol ipsec proto esp
DROP       all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save

--- Configuring RSA certificates ---

Unable to find pre-hook command /sbin/iptables in the PATH.
(PATH is /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin)
root@vpn:~# apt install iptables
Reading package lists... Done
Building dependency tree       
Reading state information... Done
iptables is already the newest version (1.8.4-3ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by jawj** [comment]
Odd that it can't find iptables. I would have thought that it would be installed as a dependency by `iptables-persistent` if for any reason it wasn't already present.

* Are you running the script as root/with `sudo`?
* Can you run `iptables` manually (try `sudo iptables -L`)?
* If not, can you install it (`sudo apt-get --reinstall install iptables`)?

**Comment by johncsuti** [comment]
>     * Are you running the script as root/with `sudo`?
Yes I am

>     * Can you run `iptables` manually (try `sudo iptables -L`)?
`root@vpn:~# sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             state NEW recent: UPDATE seconds: 300 hit_count: 60 name: DEFAULT side: source mask: 255.255.255.255
           all  --  anywhere             anywhere             state NEW recent: SET name: DEFAULT side: source mask: 255.255.255.255
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere             state INVALID
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     udp  --  anywhere             anywhere             udp dpt:isakmp
ACCEPT     udp  --  anywhere             anywhere             udp dpt:ipsec-nat-t
DROP       all  --  anywhere             anywhere            

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  10.101.0.0/16        anywhere             policy match dir in pol ipsec proto esp
ACCEPT     all  --  anywhere             10.101.0.0/16        policy match dir out pol ipsec proto esp
DROP       all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination`

>     * If not, can you install it (`sudo apt-get --reinstall install iptables`)?
Attempted to install via ./setup after reinstalling iptables. Nothing changed

**Comment by jawj** [comment]
Well, that's very strange. I've not seen this before. Perhaps worth asking in a certbot or general Ubuntu forum?

**Comment by johncsuti** [comment]
I found an issue saying that ubuntu 20.04 switched to nftables back in august of 2020. Could this be the reason iptables is broken?
https://forum.iredmail.org/post78498.html#p78498

**Comment by jawj** [comment]
Since you can run iptables manually, I wouldn't have thought so. I guess one thing to also check is `sudo which iptables` — perhaps it's not where we're expecting to find it?

**Comment by johncsuti** [comment]
root@vpn:~# which iptables
/usr/sbin/iptables

**Comment by johncsuti** [comment]
Oddly enough it works just fine running on Ubuntu 18.04. So what changed between 18.04 -> 20.04? Im not sure and i asked a friend that knows probably 4X more then i do with Ubuntu and he's not sure what's wrong.
