### ISSUE TITLE
It asks for HOST, which host?where to get it and how to configure?

### ISSUE THREAD

**Issue by Anna1w** [jawj/IKEv2-setup#129]
I even bought a domain name to point to the servers and it still did not work. Besides that I've tried editing hosts file and still same error. Please help. It doesnt want to take any values.

**Comment by jawj** [comment]
Your domain name needs to be pointed at (i.e. have an A record for the IP address of) the server you're using. You shouldn't need to edit the hosts file.

Can you clarify the way in which it isn't working?

**Comment by Anna1w** [comment]
Thank you for quick answer!
I've created an A record for the ip.
I'll disclose it:

  | A Record | boostvpn.xyz | 137.184.97.239 | Automatic |  

But when I run ./setup.sh, it asks for Hostname for VPN:
I give it a boostvpn.xyz - it says it's invalid and stops the process

I've tried to point it to vpn.boostvpn.xyz - the same thing happens
I've also noticed it asks for @ symbol in the HOST(and if I put random website with @) then it will fail after few steps

So looks like its not taking website values in "Hostname for VPN"
I don't know what to do

**Comment by Anna1w** [comment]
Also one more question, why it's necessary to have a host? I've seen many other vpn configs without that, actually it's the first time I'm seeing a Host as a requirement.

**Comment by jawj** [comment]
We need a host because we use a Let's Encrypt-issued certificate to confirm to clients that the VPN server is who it says it is, and Let's Encrypt won't issue a certificate for an IP address.

Your host doesn't seem to have a public A record. Compare:

```
% host github.com
github.com has address 140.82.121.4
github.com mail is handled by 5 alt1.aspmx.l.google.com.
github.com mail is handled by 5 alt2.aspmx.l.google.com.
github.com mail is handled by 10 alt3.aspmx.l.google.com.
github.com mail is handled by 10 alt4.aspmx.l.google.com.
github.com mail is handled by 1 aspmx.l.google.com.
``` 

and 

```
% host boostvpn.xyz
boostvpn.xyz mail is handled by 15 eforward4.registrar-servers.com.
boostvpn.xyz mail is handled by 10 eforward1.registrar-servers.com.
boostvpn.xyz mail is handled by 10 eforward2.registrar-servers.com.
boostvpn.xyz mail is handled by 10 eforward3.registrar-servers.com.
boostvpn.xyz mail is handled by 20 eforward5.registrar-servers.com.
```

(There's no "has address" line).
