### ISSUE TITLE
Connection failure on macOS Monterey 12.1

### ISSUE THREAD

**Issue by jammmet** [jawj/IKEv2-setup#133]
Hi,
I can successfully connect a linux client (strongswan / OpenWrt) to our IKEv2 server.
However, I can't get the Mac client to work after installing the `.mobileconfig`. Console shows:
```
error	15:57:38.680777+0100	NEIKEv2Provider	missing eap protocol
error	15:57:38.680794+0100	NEIKEv2Provider	empty ike proposals array
```

Any ideas?

**Comment by jawj** [comment]
Sorry for the slow reply. Looks like you switched out SHA2-384 in favour of SHA-256 (less secure), and 384-bit elliptic curve in favour of 521-bit random elliptic curve (more secure).

Seems odd that that change would fix things.

I had imagined the problem might be the same as #127.
