### ISSUE TITLE
some problems 

### ISSUE THREAD

**Issue by netscout222** [jawj/IKEv2-setup#143]
Hello !

I ran the script on a new VPS Ubuntu-20.04 and on Ubuntu-18.04

After installing it I got a notification:

Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/xx-xxx-xxx-xxx.sslip.io/fullchain.pem

I was happy that everything seemed to be fine and we could start setting up clients.   

But the file turned out to be empty /etc/ipsec.secrets   

There were no configuration files in the /home/  folder.

Well, I just in case, tried to establish a connection in Mac OS and Windows 10, but only got errors.

What can be the problem ?

Thanks for the answer !

**Comment by jawj** [comment]
It sounds rather as if setup is halting with an error somewhere.

Please paste in the full transcript of your installation session in the terminal, so we can see where things might be going wrong.
