### ISSUE TITLE
Speed limit

### ISSUE THREAD

**Issue by meteoguzhan** [jawj/IKEv2-setup#144]
Hello,
I want to set bandwidth speed limit for each user. How can I do this? is it possible?

**Comment by jawj** [comment]
This is kind of out of scope for this project.

A quick Google suggests you'll need to use `tc` (traffic control) in Ubuntu — see [this StackOverflow answer related to OpenVPN](https://serverfault.com/questions/701194/limit-throttle-per-user-openvpn-bandwidth-using-tc), for example.
