### ISSUE TITLE
Not connecting on older macOS

### ISSUE THREAD

**Issue by romatou** [jawj/IKEv2-setup#152]
After VPN setup on a new Ubuntu 20.04 I copied `.mobileconfig` to MacBook on Ventura and iPhone on iOS 16 - everything worked, but when I copied the file to my older iMac with 10.11 El Capitan - it just couldn't connect.

**What could be the issue here, any ideas?**

**Comment by jawj** [comment]
I wonder if 10.11 doesn't support the ciphers the script sets up. Worth checking the logs on both sides (as described in the README).
