### ISSUE TITLE
DNS leak Windows 11

### ISSUE THREAD

**Issue by NickManic** [jawj/IKEv2-setup#157]
It shows a leak of the original DNS. Is there any way to fix this?

**Comment by jawj** [comment]
Not a Windows expert: not sure.

How do you detect the DNS leak?

**Comment by jawj** [comment]
When setting up just now on Windows 11, I found I had to disable (or not enable) split tunnelling to have web traffic sent over the VPN:

```powershell
Set-VpnConnection -Name "vpn.example.com" -SplitTunneling $False
```

YMMV.
