### ISSUE TITLE
"The specified port is already open" error?

### ISSUE THREAD

**Issue by Mathiaszero** [jawj/IKEv2-setup#158]
Hello, 

When I connected and then disconnected successfully, I reconnected again, this error came up, shown below attached.  How can I resolve this issue? Thanks in advance.

![image](https://github.com/jawj/IKEv2-setup/assets/55817193/130a1f60-cc53-4676-840a-eadb0ce0058f)

I've read some resources that said to reinstall your network adapters and reboot, but I think that's too invasive.  Not sure what are the best methods for this.

**Comment by jawj** [comment]
Sorry, not a Windows expert, and I suspect this is really a Windows issue.

**Comment by Mathiaszero** [comment]
> Sorry, not a Windows expert, and I suspect this is really a Windows issue.

Thanks for response. It perhaps may be a Windows issue, but it appears to have implications for the server.  As sysadmin I want to ensure that the network is secure, and I see on the server side that the server still recognizes that open port even through the client that has the error is disconnected.  When I rebooted the server, it appears to disappear (not ideal as it would disconnect all other users).  

One potential scenario I can see is that the sysadmin may mistake that the credentials are compromised as there are two VPN connections (assuming that each user must only have one account at a time), but in actuality there is one with the open port error from the user and a legitimate connection by the same user if they have two profiles with the same username on the client side.

**Comment by jawj** [comment]
OK, but I think it's probably a WIndows issue (and not one I've encountered), and if not that then a Strongswan issue. I would try seeking support for those parts of the system first of all.
