### ISSUE TITLE
Config for username/password auth?

### ISSUE THREAD

**Issue by kaizenblumenblupper** [jawj/IKEv2-setup#162]
Many thanks for your script, it works nicely! But I have a very specific demand for my server - I need to connect not with .mobileconfig, but with username/password pair. And it seems I can get no solution for that.
Is there a way to?

**Comment by jawj** [comment]
Can you explain this more clearly? Which sort of device are you trying to connect?

On iOS and Mac a .mobileconfig is needed to set up sufficiently secure ciphers: entering a username and password into the VPN UI hasn't ever worked for me.

You might also be able to achieve the same result with a custom program using Apple's VPN APIs.

Alternatively, you could set the server to offer very weak ciphers if that's good enough for your use case.

**Comment by kaizenblumenblupper** [comment]
@jawj the reason is that on iOS there are two types of VPN entries - "Device VPN" and "Personal VPN". They can work together simultaneously and that's what I need, as I have a constantly working Device VPN entry for an app Lockdown, which is a firewall which works like a "local" VPN to filter traffic.

![vpn settings screenshot](https://github.com/user-attachments/assets/c23f7590-c7f7-47ce-8625-2000570acda8)
Screenshot example for demo, not actually from my device.

The problem is a "Personal VPN" entry can only be added through an app which uses specific API. 
There is one like that, Brooog IKEv2, and it requires username/password auth method to add VPN config and can't take .mobileconfig files or a certificate based method.
That's the only reason, but it's crucial

**Comment by jawj** [comment]
OK, well this script does set up user/password auth using EAP-MSCHAPv2, which is what Brooog says it wants.

Have you tried simply entering the VPN username and password you specified at server set-up time in the Brooog app?

**Comment by jawj** [comment]
It doesn't seem to work as-is:

```
Aug 28 09:28:10 VPN ipsec[620]: 12[CFG] received proposals: IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_2048
Aug 28 09:28:10 VPN ipsec[620]: 12[CFG] configured proposals: IKE:AES_GCM_16_256/PRF_HMAC_SHA2_384/ECP_384, IKE:AES_GCM_16_256/PRF_HMAC_SHA2_256/ECP_256
Aug 28 09:28:10 VPN ipsec[620]: 12[IKE] remote host is behind NAT
Aug 28 09:28:10 VPN ipsec[620]: 12[IKE] received proposals unacceptable
```

So you either need to ask Brooog to support more secure ciphers, or you can modify the server setup to support the less secure ciphers the Brooog app is proposing.

**Comment by kaizenblumenblupper** [comment]
@jawj oh, I'm very sorry to bother you with such questions, but it seems after all the investigations I can't figure out how to set it up correctly 🤯
I add user/password into ipsec.secrets - no connection. I add weaker ciphers in ipsec.conf - the same problem. 
That all just blows my mind, despite I have some coding background. 

Couldn't you please share any "understandable" guide on these things? That's all too unintuitive

**Comment by jawj** [comment]
`sudo nano /etc/ipsec.conf`, delete the `ike = ...` and `esp = ...` lines with Ctrl-K, save with Ctrl-O [Return], exit with Ctrl-X.

`sudo ipsec restart` and the Broog app should now connect using whatever ciphers it likes, though this may not be very secure.

`/etc/ipsec.secrets` should already have the username and password you set at install time, though you can add more.

**Comment by kaizenblumenblupper** [comment]
Oh, I'm so sorry for a very late reply, but you literally saved me @jawj! Many many thanks, it seems now my VPN finally is up and running :)
I couldn't have figured all that out by myself, for sure. Awesome!
