### ISSUE TITLE
ipsec.conf

### ISSUE THREAD

**Issue by jammmet** [jawj/IKEv2-setup#17]
I'm got this running swimmingly on a macOS client. However, which config options do I need to make it work on a linux (OpenWRT) client? I've got so far as adding the following to `ipsec.conf`:

    conn [conn_name]
    right=[host]
    rightid=%[host]
    rightsubnet=0.0.0.0/0
    rightauth=pubkey
    leftsourceip=%config
    leftauth=eap
    eap_identity=[username]
    auto=add

Ideally I'd have it save the user's password too, instead of asking every time. Apologies - new to Strongswan!

**Comment by jawj** [comment]
On Ubuntu, this works for me:

    apt-get install strongswan libstrongswan-standard-plugins libcharon-standard-plugins libcharon-extra-plugins
    ln -s /etc/ssl/certs/DST_Root_CA_X3.pem /etc/ipsec.d/cacerts/

Then in `ipsec.conf`:

    conn %default
            ikelifetime=60m
            keylife=20m
            rekeymargin=3m
            keyingtries=1
            keyexchange=ikev2
    
    conn myvpn
            leftsourceip=%config
            type=tunnel
            leftauth=eap-mschapv2
            eap_identity=myusername
            right=myvpn.example.com
            rightauth=pubkey
            rightid=@myvpn.example.com
            auto=add

Change to `auto=start` if you want to connect automatically.

Finally, in `ipsec.secrets`:

    myusername %any : EAP "mypassword"

**Comment by jawj** [comment]
I updated the previous message based on some further testing. Let me know if this works for you.

**Comment by jawj** [comment]
Based on this I have now added an Ubuntu setup script to the client configuration files generated by the server setup script.
