### ISSUE TITLE
Failed update strongswan from apt get

### ISSUE THREAD

**Issue by ookangzheng** [jawj/IKEv2-setup#18]
<img width="1173" alt="screen shot 2017-06-20 at 15 46 48" src="https://user-images.githubusercontent.com/6301735/27322220-d9d28fc4-55cf-11e7-94ce-af21402a1863.png">
how to fix it?

**Comment by jawj** [comment]
Can you give a bit of context? I'm not sure where you're getting strongSwan 5.5.2 from, since I can only find 5.5.1 in Ubuntu packages (even up to the forthcoming artful release). https://packages.ubuntu.com/zesty/strongswan

**Comment by ookangzheng** [comment]
I just apt-update and apt-upgrade then it shows Strongswan 5.5.2 update than I get error

**Comment by jawj** [comment]
I'm afraid I can't recreate this issue, so I'm closing, until/unless anyone can shed any more light.
