### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by leonguyen52** [jawj/IKEv2-setup#21]
I just upgraded my server from Ubuntu 16.04 to 17.04 and installed your script but it showed error as follow:

> Setting up libstrongswan-extra-plugins (5.5.1-1ubuntu3.1) ...
> Processing triggers for ureadahead (0.100.0-19) ...
> Processing triggers for libc-bin (2.24-9ubuntu2.2) ...
> Processing triggers for systemd (232-21ubuntu5) ...
> Processing triggers for ufw (0.35-4) ...
> Errors were encountered while processing:
>  postfix
>  mailutils
> E: Sub-process /usr/bin/dpkg returned an error code (1)

How can I solve it? Thank you.

**Comment by leonguyen52** [comment]
I figured it out. It's my mistake on setting hostname. Thank you.

**Comment by jawj** [comment]
OK — great! 

I was about to say: the script expects to start from a clean installation, and sets up the whole box, not just the VPN software. Perhaps your box already has postfix and/or mailutils (or some conflicting mail-related packages) installed? But sounds like I was wrong.
