### ISSUE TITLE
DNS

### ISSUE THREAD

**Issue by adamluk** [jawj/IKEv2-setup#24]
Hello,

I wonder if it may be worth adding in a note about using alternative non logging DNS services, rather than Google's resolvers?

There's a good list available here: https://www.lifewire.com/free-and-public-dns-servers-2626062

For what it's worth I have found DNS.WATCH to be very reliable.

**Comment by jawj** [comment]
Good idea! I may do some experimentation and consider switching the DNS settings to DNS.WATCH.

**Comment by adamluk** [comment]
Like I say I've always found DNS.WATCH to be reliable. They are non logging and generally well thought of. I have previously used an OpenVPN script from Nyr, and a fork of this script from Angristan. I used this as inspiration to propose a similar implementation in your script. I've put through a pull request so you're welcome to do with it as you please. Thanks again for putting this together, it has proved very useful 👍

**Comment by jawj** [comment]
Thanks Adam. I am mulling whether to include your menu (thanks for this) or just change the default to DNS.WATCH and provide the other options in the docs for advanced users ...

**Comment by jawj** [comment]
I've added a choice of DNS servers as an additional step at installation.
