### ISSUE TITLE
certbot package not available 

### ISSUE THREAD

**Issue by discrob** [jawj/IKEv2-setup#3]
I attempted to use your script on a fresh 16.04 installation and i was unable to to complete due to certbot package not being available for ubuntu?

**Comment by jawj** [comment]
Thanks @jarz, that's exactly it. AFAIK the `letsencrypt` package on 16.04 isn't a perfect substitute — it doesn't set up autorenewal cron jobs, for example. That's why I went for 16.10, even though it will require an upgrade/rebuild for 17.04 before too long.
