### ISSUE TITLE
connecting from ios

### ISSUE THREAD

**Issue by davisbra** [jawj/IKEv2-setup#30]
I use setup.sh and its working correctly.I can connect from strongswan android client and for ios ,I install .mobileconfig and it works.
my question is how can I connect programmatically in ios using xcode?
I use multiple samples for IKEv2 connection in ios but not working some of the samples need certificate file for connection(.p12).
how cat I export .p12 certificate?

**Comment by jawj** [comment]
Not sure, but you probably shouldn't need a cert file since the certificate is from LetsEncrypt and trusted by default.

**Comment by gang018** [comment]
> I use setup.sh and its working correctly.I can connect from strongswan android client and for ios ,I install .mobileconfig and it works.
> my question is how can I connect programmatically in ios using xcode?
> I use multiple samples for IKEv2 connection in ios but not working some of the samples need certificate file for connection(.p12).
> how cat I export .p12 certificate?

did you solve your problem?
