### ISSUE TITLE
Configure VPN connection via Windows 7/10 GUI

### ISSUE THREAD

**Issue by g00ntar** [jawj/IKEv2-setup#32]
I'm interested in how to modify this script to allow connection via Windows gui in network manager. For my purposes - easy use for NOT IT people - this would be better. Thanks for your help.

**Comment by jawj** [comment]
Looking at the commit history, I see:

_Updated ciphers for better Windows 10 security (via PowerShell)_

```
   keyexchange=ikev2
   fragmentation=yes
   forceencaps=yes
-  ike=aes256gcm16-sha256-ecp521,aes256-sha256-modp1024!
-  esp=aes256gcm16-sha256,aes256-sha1!
+  ike=aes256gcm16-sha256-ecp521,aes256-sha256-ecp384!
+  esp=aes256gcm16-sha256!
   dpdaction=clear
   dpddelay=180s
   rekey=no
```

So I think it might work if you tack on extra ciphers to give the following, on lines 227 – 228:

```
  ike=aes256gcm16-sha256-ecp521,aes256-sha256-ecp384,aes256-sha256-modp1024!
  esp=aes256gcm16-sha256,aes256-sha1!
```

**Comment by haofeiyan** [comment]
Default Windows 10 IKEv2 VPN is weak. If you insist to use GUI, you could try Registry Solution.
[http://www.stevenjordan.net/2016/09/secure-ikev2-win-10.html](url)

**Comment by jawj** [comment]
I don't see a lot of point configuring an extremely weak VPN, so I don't plan on weakening the encryption in the project. You should feel free to tweak your own config, of course.
