### ISSUE TITLE
External IP and Internal IP mixup

### ISSUE THREAD

**Issue by houmie** [jawj/IKEv2-setup#34]
Hello,

This seems like a wonderful project. I installed it on a Google Compute instance (Ubuntu 17.04).

During the installation, I get the following error:

```
Processing triggers for ufw (0.35-4) ...

Network interface: ens4
External IP: 10.142.0.2
Warning: vpn.myDomain.com resolves to 104.196.47.118, not 10.142.0.2
Either you are behind NAT, or something is wrong (e.g. hostname points to wrong IP, CloudFlare proxying shenanigans, ...)
Press [Return] to continue, or Ctrl-C to abort
```

Well, my external IP of the instance is 104.196.47.118 and the internal IP is 10.142.0.2. Why should my domain point to the internal IP address? That makes no sense.

May you please advise on this?

Many Thanks,
Houman

**Comment by houmie** [comment]
I did further investigation into the script:

The issue is here when you check if IP of network is not equal to VPN IP address:
```
if [[ "$IP" != "$VPNHOSTIP" ]]; then
```
You get IP like this:
```
ETH0ORSIMILAR=$(ip route get 8.8.8.8 | awk -- '{printf $5}')
IP=$(ifdata -pa $ETH0ORSIMILAR)
```
On AWS this becomes like `ifdata -pa eth0`
But this returns always the internal IP address on AWS.

I'm not sure on which provider, you've tested this.  Google Compute Engine has the exact same issue.

Many Thanks,
Houman

**Comment by houmie** [comment]
@jawj Sorry George to be a pest, I just wonder if this is something you could look into or should I rather install StrongSwan by hand. Just in case that this project is no longer actively supported. Many Thanks

**Comment by jawj** [comment]
Hi @houmie. It seems like perhaps we're getting the external IP wrong on some providers. I think it says where I've tested it in the README — OVH, Vultr, Linode, possibly others. The project is supported to the extent that I have time, which is often pretty limited. I'll look into this when I can. Meanwhile, do let me know if you find a more reliable way to get the external IP.
