### ISSUE TITLE
Won't Connect after iOS 11 and 10.13 High Sierra

### ISSUE THREAD

**Issue by scottyloveless** [jawj/IKEv2-setup#35]
Hey I'm having trouble connecting using this script on the new software. I figured it was something on Apple's end but just wanted to post something on here.

Tried on iOS 11.0.3 and macOS 10.13.0.

Anybody else having the same trouble?

Things I've tried:
1. Rebooting the server
2. Rebooting Phone
3. Fresh install of iOS 11 & High Sierra
4. Reinstalling the mobileconfig profile.
5. Tested and same VPN profile connects on older software (iOS 10 and macOS 10.12.6)

**Comment by jawj** [comment]
Hmm, strange. I haven't yet upgraded to High Sierra, but I've had no trouble on my iPhone after upgrading to iOS 11. 

Have you tried checking the log files on both client and server, as described in the [README](https://github.com/jawj/IKEv2-setup#troubleshooting)?

I'll keep this open — has anyone else seen anything go awry?

**Comment by scottyloveless** [comment]
For some reason it just started working again. ¯\_(ツ)_/¯ Closing, thanks!

**Comment by jawj** [comment]
Great. I have now updated to High Sierra too and not spotted any issues so far.
