### ISSUE TITLE
why ssh username/password/port is needed ?

### ISSUE THREAD

**Issue by anphorea** [jawj/IKEv2-setup#38]
when I execute this script with root via ssh,
it still asks me about my ssh port / username / password,
I don't want to create a new user / port ,
please fix this . thanks .

**Comment by jawj** [comment]
The script is designed to set up the server from scratch, including creating a non-root user account for the box that you can then SSH in with. From my point of view, there is nothing to fix.

Of course, if you want the script to do something different, you are welcome to fork it and amend.
