### ISSUE TITLE
Problem with <key>OnDemandEnabled</key> 

### ISSUE THREAD

**Issue by Bougakov** [jawj/IKEv2-setup#40]
Please consider removing this setting from generated mac/iphone config. 

It can be overridden in iOS but not in MacOS (in latter VPN stays lways on as the result).

**Comment by yakovmanshin** [comment]
You can yourself edit the .mobileconfig file in any text editor (like TextEdit) and disable on-demand connection: just replace 1 with 0 in the following code.

```
<key>OnDemandEnabled</key>
<integer>1</integer>
```

**Comment by jawj** [comment]
It can be overridden in MacOS.

Go to: 
System Preferences > Network > vpn.example.com

And uncheck:
[x] Connect on demand

**Comment by Bougakov** [comment]
> It can be overridden in MacOS.

Strangely it can't. Tested on macOS 10.13 High Sierra - checkbox becomes disabled in checked state.

**Comment by jawj** [comment]
Odd — it works for me on 10.13. Does your user account have admin privileges? Not sure what else could account for the difference.

**Comment by yakovmanshin** [comment]
Have you unlocked the Network preferences pane by clicking the lock icon in the bottom left?
