### ISSUE TITLE
Connection established then I get disconnected automatically after downloading things

### ISSUE THREAD

**Issue by TheyCantHandle** [jawj/IKEv2-setup#42]
I have another issue, whenever I start torrenting using my VPN, it seems like after few minutes or seconds the vpn dies and I have to manually reconnect to it (I get disconnected automatically). Is this related to performance issues or more like few settings I could change?

**Comment by TheyCantHandle** [comment]
Edit :  in windows 10 gui it shows as I am still connected, but no connection when I try to browse web content or download anything

**Comment by jawj** [comment]
I have now updated the ESP settings (see #55), which might possibly help. If you're still seeing this issue, please check the logs as directed in the Troubleshooting section of the README.
