### ISSUE TITLE
loading private key from '/etc/ipsec.d/private/privkey.pem' failed

### ISSUE THREAD

**Issue by stevesanda** [jawj/IKEv2-setup#46]
Hello

I have run the setup.sh on two VPS machines using linode and ran into the same issue each time. Everything seems to setup properly, but when it comes to connecting with my first device, nothing seems to work (the first device I try is an iPhone and the VPN status bounces between 'Connected' and 'Not Connected' repeatedly).

From /var/log/syslog (xxx is server and yyy is client):

> Dec 17 03:25:09 LNVPN1 charon: 12[NET] sending packet: from xx.xxx.xxx.xxx[4500] to yyy.yyy.yyy.yyy[4718] (65 bytes)
Dec 17 03:25:10 LNVPN1 charon: 13[NET] received packet: from yyy.yyy.yyy.yyy[500] to xxx.xxx.xxx.xxx[500] (300 bytes)
Dec 17 03:25:10 LNVPN1 charon: 13[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(REDIR_SUP) N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) ]
Dec 17 03:25:10 LNVPN1 charon: 13[IKE] yyy.yyy.yyy.yyy is initiating an IKE_SA
Dec 17 03:25:10 LNVPN1 charon: 13[IKE] remote host is behind NAT
Dec 17 03:25:10 LNVPN1 charon: 13[ENC] generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(MULT_AUTH) ]
Dec 17 03:25:10 LNVPN1 charon: 13[NET] sending packet: from xxx.xxx.xxx.xxx[500] to 173.18.16.137[500] (316 bytes)
Dec 17 03:25:40 LNVPN1 charon: 11[JOB] deleting half open IKE_SA after timeout

When I run `ipsec rereadsecrets` some part of the issue seems to appear:

> Dec 17 03:26:02 LNVPN1 charon: 12[CFG] rereading secrets
Dec 17 03:26:02 LNVPN1 charon: 12[CFG] loading secrets from '/etc/ipsec.secrets'
Dec 17 03:26:02 LNVPN1 charon: 12[LIB]   opening '/etc/ipsec.d/private/privkey.pem' failed: No such file or directory
Dec 17 03:26:02 LNVPN1 charon: 12[LIB] building CRED_PRIVATE_KEY - RSA failed, tried 11 builders
Dec 17 03:26:02 LNVPN1 charon: 12[CFG]   loading private key from '/etc/ipsec.d/private/privkey.pem' failed
Dec 17 03:26:02 LNVPN1 charon: 12[CFG]   loaded EAP secret for vpn-iphone %any

When I look into the `etc/ipsec.d/private/` directory, there is a file in there...furthermore there are files in the `/etc/letsencrypt/live/(hostname)` folders.

Not sure what to try to clear this up.

**Comment by stevesanda** [comment]
FYI in order to correct the issue, I had to remove the symbolic links and copy the letsencrypt pem files into their respective ipsec.d folders. This is a bummer since the update of the letsencrypt certs won't be automatic.

Reference this thread: https://groups.google.com/forum/#!topic/strongswan-users/wmnQaJ52FNo

**Comment by jawj** [comment]
Hmm, this is odd, since I have a VPN on Linode using this script. I agree that copying the files is no real solution, because that will mean manual intervention every 90 days.

I previously ran into a similar problem caused by AppArmor settings, but I had thought that was fixed. If you could confirm whether it's AppArmor — probably by setting AppArmor to 'complain' instead of 'enforcement' mode — that would be very helpful.

**Comment by jawj** [comment]
I'll reopen if I hear back on this ...
