### ISSUE TITLE
unable to login from windows 7 and ios device

### ISSUE THREAD

**Issue by legale** [jawj/IKEv2-setup#48]
Hello. First of all, you have made very nice script. I got scaleway VPS. Lateset ubuntu is 17.04 so i did some changes.

1. allow to start from 17.04 ubuntu
2. add dig command check and install dnsutils if not

On my android device with strongswan app installed everything is ok. But i'm unable to connect to sever from any other device. IOS with script generated config and windows 7/10 with default vpn client.

What should i do to make it work?

Thank you

**Comment by xlighting2017** [comment]
Q1:  did your VPS instance has a valid Domain Name?  

Q2: does the script run with any error?

Q3: have you receive the mail? you have installed the config file on your iPhone? any fail/error message?

**Comment by legale** [comment]
a1: yes, VPS has got valid domain name.
a2: no, script completed without any errors.
a3: yes, config is ok and installed correctly.

Something wrong with strongSwan i think. because i've tried libreSwan with
PSK  ikev1 - everything is ok.

**Comment by jawj** [comment]
Have you checked the server and client logs, as suggested in the Troubleshooting section of the README?

**Comment by jawj** [comment]
Closing pending further feedback ...
