### ISSUE TITLE
Verification fails

### ISSUE THREAD

**Issue by pokeacer** [jawj/IKEv2-setup#50]
On the regular script, verification will fail with timeout due to IPTables being set to deny all but HTTPS. however, the command used by certbot is HTTP; I had to edit my setup.sh to allow (and then deny) port **80** not 443. This should be added into the script if possible (I'd PR but I don't know if there's a better way)

**Comment by klvs** [comment]
Also experiencing this. @pokeacer can you share the edits you made?

**Comment by pokeacer** [comment]
I sincerely apologise for leaving this so long: https://i.fl0.co/6skgm5.sh is my modified script that allows the correct port.

**Comment by jawj** [comment]
The port used by certbot could be 80 or 443, and I open port 443 in the pre-hook. This has always worked for me, but I have just added the `--preferred-challenges tls-sni` option to the certbot command to ensure it always uses 443. It should not be necessary therefore to make any other changes. Please let me know if that doesn't work.

**Comment by Omid-Shojaee** [comment]
Port 443 never worked for me and when I discussed it with LetsEncrypt community they told me it is disabled for security reasons (https://community.letsencrypt.org/t/timeout-error-on-fetching/50775)

Also, tls-sni is disabled permanently https://community.letsencrypt.org/t/important-what-you-need-to-know-about-tls-sni-validation-issues/50811

**Comment by muplagama** [comment]
i have the same problem, i dont know. the installation was canceled

**Comment by Omid-Shojaee** [comment]
Edit the script, find pre-hook and post-hook and change 443 to 80. Port 443 is disabled by LetsEncrypt but jawj refuses to accept this fact.

**Comment by muplagama** [comment]
Cleaning up challenges
Running post-hook command: /sbin/iptables -D INPUT -p tcp --dport 80 -j ACCEPT
Failed authorization procedure. vpn.neuro-wittenberg.de (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://vpn.xxx.de/.well-known/acme-challenge/WnPS1y_JRfy0QFbg223mpH5Iv1rf4k_2OwJJMCNMnBg: Timeout

**Comment by Omid-Shojaee** [comment]
Are you 100% sure your hostname resolves to correct IP address?
Please paste your CERTBOT command as well.

**Comment by muplagama** [comment]
-server behind a NAT

Network interface: eth0
External IP: 192.168.100.97
Warning: vpn.xxx.de resolves to 80.151.226.97, not 192.168.100.97
Either you are behind NAT, or something is wrong (e.g. hostname points to wrong IP, CloudFlare proxying shenanigans, ...)
Press [Return] to continue, or Ctrl-C to abort

--- Configuring firewall ---

Chain INPUT (policy ACCEPT)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             state NEW recent: UPDATE seconds: 60 hit_count: 12 name: DEFAULT side: source mask: 255.255.255.255
           all  --  anywhere             anywhere             state NEW recent: SET name: DEFAULT side: source mask: 255.255.255.255
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere             state INVALID
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     udp  --  anywhere             anywhere             udp dpt:isakmp
ACCEPT     udp  --  anywhere             anywhere             udp dpt:ipsec-nat-t
DROP       all  --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  10.10.10.0/24        anywhere             policy match dir in pol ipsec proto esp
ACCEPT     all  --  anywhere             10.10.10.0/24        policy match dir out pol ipsec proto esp
DROP       all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

--- Configuring RSA certificates ---

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Running pre-hook command: /sbin/iptables -I INPUT -p tcp --dport 80 -j ACCEPT
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for vpn.xxx.de
Waiting for verification...
Cleaning up challenges
Running post-hook command: /sbin/iptables -D INPUT -p tcp --dport 80 -j ACCEPT
Failed authorization procedure. vpn.xxx (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://vpn.xxx.de/.well-known/acme-challenge/Ydh4qkHOOX9aewpc2v2880tUxZHUX75X480MwdZz18Q: Timeout

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: vpn.xxx.de
   Type:   connection
   Detail: Fetching
   http://vpn.xxx.de/.well-known/acme-challenge/Ydh4qkHOOX9aewpc2v2880tUxZHUX75X480MwdZz18Q:
   Timeout

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

**Comment by muplagama** [comment]
i need an webserver-service like nginx or apache or runs standalone without it?

**Comment by muplagama** [comment]
i have forward port 4500 & 500 (DDP) and 443 & 80 (TCP) to the internal lan ip.
the same server runs since a half year with the old installation-script and port 443 but not with reinstalled new installation-script and port 80

**Comment by Omid-Shojaee** [comment]
I suggest you discuss your issue with LetsEncrypt community. I am sure they have faced this condition before and are able to help you.

**Comment by jawj** [comment]
I have changed the challenge to http and the temporarily-opened port to 80.

**Comment by jawj** [comment]
In the absence of further feedback I'm assuming this works for you all!
