### ISSUE TITLE
ERROR: /etc/ipsec.conf: 9: keyword keyexchange, invalid value: ikev2

### ISSUE THREAD

**Issue by AndreasOttenNetherlands** [jawj/IKEv2-setup#51]
Hi, thanks for the script didnt get ikev2 to working after a few tutorials etc.
But now i get the following error with your script: ERROR: /etc/ipsec.conf: 9: keyword keyexchange, invalid value: ikev2
Is the problem in the current ubuntu package?

**Comment by jawj** [comment]
Which Ubuntu version are you using? It works for me on 17.10.

**Comment by AndreasOttenNetherlands** [comment]
I was using 17.10 but guess it was because i was running it on an armhf cpu. (rock 64)

**Comment by jawj** [comment]
Ah — OK. In that case, closing.

**Comment by rogeliotrejo13** [comment]
Hello I have same issue, Debian Buster migrating strongswan to libreswan

**Comment by jawj** [comment]
@rogeliotrejo13 The script aims to set up strongSwan on Ubuntu, so I'm afraid this problem sounds pretty seriously out of scope.
