### ISSUE TITLE
--preferred-challenges tls-sni breaks installation

### ISSUE THREAD

**Issue by Bougakov** [jawj/IKEv2-setup#53]

**Comment by Bougakov** [comment]
This flag is unnecessary, it was fixed in https://github.com/certbot/certbot/issues/5405

**Comment by Omid-Shojaee** [comment]
tls-sni is disabled by LetsEncrypt for security reasons. It should be changed to http-01 to work.

**Comment by jawj** [comment]
I have changed the preferred challenge to http and temporarily open port 80 instead of 443.
