### ISSUE TITLE
Syntax error: Will not run on fresh Ubuntu Server install

### ISSUE THREAD

**Issue by qrx** [jawj/IKEv2-setup#59]
```
root@server:~# ./setup.sh
./setup.sh: line 7: syntax error near unexpected token `newline'
./setup.sh: line 7: `<!DOCTYPE html>'
```

Can someone help explain this? The script complains of a syntax error. I'm running a fresh install of the recommended OS.

**Comment by jawj** [comment]
Looks like you've managed to save an HTML file from Github instead of the raw script? You need this link: https://raw.githubusercontent.com/jawj/IKEv2-setup/master/setup.sh

**Comment by qrx** [comment]
Forgive me. I'm slightly dumb 👍
