### ISSUE TITLE
Feature Request: letsencrypt DNS challenge support

### ISSUE THREAD

**Issue by Cave-Johnson** [jawj/IKEv2-setup#61]
Would it be possible to give the user the option to support let's encrypt via DNS challenges instead? Some environments it is not possible to have port 80 open to internet (NAT / already in use).

In the past I have used acme.sh with cloudflare and it works like a charm. also possible with other service APIs
https://github.com/Neilpang/acme.sh/blob/master/dnsapi/README.md

**Comment by jawj** [comment]
Happy to receive pull requests, but not a high priority for me right now, I'm afraid.
