### ISSUE TITLE
function: not found

### ISSUE THREAD

**Issue by FileDotExe** [jawj/IKEv2-setup#65]
Hi, I've used this script in the past and had no issues with it, but I recently changed hosting providers and tried to reinstall using your script, and I keep getting "setup.sh: 16: setup.sh: function: not found". Any help would be very appreciated! Thanks! 
![image](https://user-images.githubusercontent.com/23145817/44639736-156bdb00-a983-11e8-9652-8c61d19360ae.png)

**Comment by jawj** [comment]
Seems most likely the script is being run under some other, non-Bash shell, which doesn't understand the function keyword. Can you make sure you're running it with Bash?

**Comment by FileDotExe** [comment]
:P I was running it with sh instead of bash, my bad. Sorry for wasting your time. Have a great day!
