### ISSUE TITLE
May I use it on the server with SOCKS proxy installed

### ISSUE THREAD

**Issue by syabro** [jawj/IKEv2-setup#67]
I'm not sure so asking :) Like does it blocks all ports f.e.?

**Comment by jawj** [comment]
I don't know anything much about running a SOCKS proxy, but yes, you'd likely need to open up the firewall for it.

**Comment by syabro** [comment]
@jawj how can I do it? It needs 33080 port to be opened
I guess something about `iptables` but I don't know it at all

**Comment by jawj** [comment]
I suggest you do a bit of reading up on `iptables` (e.g. https://www.howtogeek.com/177621/the-beginners-guide-to-iptables-the-linux-firewall/) and use the existing commands (starting around line 100 of `setup.sh`) as a model.

**Comment by syabro** [comment]
@jawj thanks
