### ISSUE TITLE
Static (fixed) IP address for second user

### ISSUE THREAD

**Issue by euglv** [jawj/IKEv2-setup#68]
Hi, thank you for your script.

I am having troubles to setup second VPN user with fixed IP inside VPN network.
Your script configures one VPN user that receives free IP from pool `10.10.10.0/24`
I want to change IPs for that user to be in range `10.10.10.11-10.10.10.254`. 
I figured out that to do this I need to modify `rightsourceip=` of `conn roadwarrior` section in `/etc/ipsec.conf`
I know how to add new users in `\etc\ipsec.secrets`, but they receive IPs from the same pool.

As I understand, I need to setup additional `conn` sections for each VPN user that requires fixed IP in `/etc/ipsec.conf`

The problem is, if I modify `leftid=` or `eap_identity=` fields of `conn roadwarrior` section to something other than `%any` - then I can't connect to VPN server using Windows 10 and Ubuntu anymore, only Android StrongSwan application is able to connect.

What is the correct way to configure `/etc/ipsec.conf` to make some VPN users receive IP from pool and make other VPN users to have fixed IP?

**Comment by Fastidious** [comment]
Not the owner of the project, @euglv, but I am sure this is out of the scope of the script. Maybe asking over [strongSwan](https://www.strongswan.org/support.html)?
