### ISSUE TITLE
Suggested ciphers in ipsec.conf cause issues with Windows 10

### ISSUE THREAD

**Issue by Bougakov** [jawj/IKEv2-setup#72]
I used your suggested values for ike and esp parameters in ipsec.conf:

https://github.com/jawj/IKEv2-setup/blob/475eabb5c8cf08bad68496034da5491edf45b226/setup.sh#L233

turns out that they cause Windows 10 to fail the VPN connection after some time. I've created a ticket in StrongSwan tracker and got [this explanation:](https://wiki.strongswan.org/issues/2808?issue_count=262&issue_position=1&next_issue_id=2807#note-5)

> [Windows 10] tries to rekey the CHILD_SA, but that fails, because you did not configure PFS on the server side, but the Windows client wants to use PFS.
> You need to change your phase two cipher configuration to use PFS with ecp384.
> That looks like that: `esp=aes256gcm16-ecp384`
> Also, your cipher proposals in phase one are invalid.

https://github.com/jawj/IKEv2-setup/blob/475eabb5c8cf08bad68496034da5491edf45b226/setup.sh#L232

> Change `ike=aes256gcm16-sha256-ecp521,aes256-sha256-ecp384!` to `ike=aes256gcm16-prfsha256-ecp521,aes256-sha256-ecp384` to make them valid. You can not propose a HMAC with AEAD algorithm. the AEAD algorithm always provides confidentiality and authenticity for the messages. You can not mix that and make the HMAC provide authenticity and the AEAD algorithm only confidentiality.

**Comment by jawj** [comment]
@Bougakov Thanks, this is very helpful feedback. Those new `ike` and `esp` options seem to work well in iOS, macOS and Windows 10. I think I might need to update the .mobileconfig and Ubuntu client configs to match, though, which is the only reason I'm not making the change immediately. I'll keep you posted ...

**Comment by Bougakov** [comment]
No need to alter .mobileconfig - it works. Check out mine - it required no changes: https://v.bougakov.com/assets/setupfiles/vpn.mobileconfig (ignore that it is signed)

**Comment by jawj** [comment]
As you wrote in your thread at strongswan — choosing ciphers is evidently above my paygrade too! Thanks for filing this issue, though. The setup is now both more reliable and more secure.
