### ISSUE TITLE
Feature request: suggest using sslip.io for those who don't have a domain, just IP address

### ISSUE THREAD

**Issue by Bougakov** [jawj/IKEv2-setup#74]
Hi. Small feature request. There is a service called sslip.io that provides a domain name for any IP address. If, say, you have IP 1.2.3.4 provided by DigitalOcean or Hetzner with their cheap $3 virtual server, you can access it as 1.2.3.4.sslip.io - and, most importantly, issue a Let's encrypt certificate for it. It is a workaround for those who can't afford a domain name and are OK to depend on free service.

I suggest offering it somewhere near https://github.com/jawj/IKEv2-setup/blob/475eabb5c8cf08bad68496034da5491edf45b226/setup.sh#L28

**Comment by jawj** [comment]
Thanks, I was looking for something along these lines just the other day. An sslip.io hostname is now assigned automatically if no hostname is entered at the prompt.
