### ISSUE TITLE
Feature request: propose to enable SplitTunneling in Windows 10

### ISSUE THREAD

**Issue by Bougakov** [jawj/IKEv2-setup#76]
Hi. I suggest minor improvement. You can prompt the user something like

> "Do you have printers, file servers, media players in your local network you'd like to remain available while you are using VPN? (answer No if you will be mostly using VPN on public networks, not home network)"

If the user agrees, add

`Set-VpnConnection -Name "${VPNHOST}" -SplitTunneling $True`

to the bottom of the generated PowerShell script.

**Comment by jawj** [comment]
Hmm — according to the [strongSwan docs](https://wiki.strongswan.org/projects/strongswan/wiki/ForwardingAndSplitTunneling):

> Windows 10 has split tunneling enabled by default, but with the same limitations seen since Windows 7, i.e. the virtual IP has to be from the remote subnet, or routes have to be added manually, for instance, via Add-VpnConnectionRoute PowerShell command.
>
> To tunnel all traffic via VPN instead, split tunneling has to be disabled explicitly, either by enabling the Use default gateway on remote network setting described above or by using the following PowerShell command: Set-VpnConnection "<Connection Name>" -SplitTunneling 0

However, when I create a connection using PowerShell commands, SplitTunneling does appear to be off by default.

I don't want to ask any more questions when the script is run, so instead I'll probably add the appropriate line at the end of the PowerShell config, with a comment explaining when you would want to run it.

**Comment by Bougakov** [comment]
"Use default gateway on remote network setting" is set by default. Disabling it caused www.whatismyip.com to display my real IP address instead of VPN server's. So it turns out that "split tunneling" is the best option.
