### ISSUE TITLE
no IKE config found for 10.0.0.2...5.79.68.xxx, sending NO_PROPOSAL_CHOSEN

### ISSUE THREAD

**Issue by maciekish** [jawj/IKEv2-setup#8]
Hi, i used this script but cannot connect with the following errors. The server is Ubuntu 16.10 behind NAT with UDP 500 & 4500 forwarded. The client is iOS 10 on a public LTE network.

I find it a bit confusing that there are two external ip's mentioned. Is my mobile operator doing something funky?

	Mar 15 11:37:00 mainframe charon-custom: 09[NET] received packet: from 94.254.161.xxx[11684] to 10.0.0.2[500] (308 bytes)
	Mar 15 11:37:00 mainframe charon-custom: 09[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(REDIR_SUP) N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) ]
	Mar 15 11:37:00 mainframe charon-custom: 09[IKE] 94.254.161.xxx is initiating an IKE_SA
	Mar 15 11:37:00 mainframe charon-custom: 09[IKE] local host is behind NAT, sending keep alives
	Mar 15 11:37:00 mainframe charon-custom: 09[IKE] remote host is behind NAT
	Mar 15 11:37:00 mainframe charon-custom: 09[ENC] generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(MULT_AUTH) ]
	Mar 15 11:37:00 mainframe charon-custom: 09[NET] sending packet: from 10.0.0.2[500] to 94.254.161.xxx[11684] (316 bytes)
	Mar 15 11:37:05 mainframe charon-custom: 11[NET] received packet: from 5.79.68.xxx[48661] to 10.0.0.2[500] (192 bytes)
	Mar 15 11:37:05 mainframe charon-custom: 11[ENC] parsed ID_PROT request 0 [ SA ]
	Mar 15 11:37:05 mainframe charon-custom: 11[IKE] no IKE config found for 10.0.0.2...5.79.68.xxx, sending NO_PROPOSAL_CHOSEN
	Mar 15 11:37:05 mainframe charon-custom: 11[ENC] generating INFORMATIONAL_V1 request 1899030108 [ N(NO_PROP) ]
	Mar 15 11:37:05 mainframe charon-custom: 11[NET] sending packet: from 10.0.0.2[500] to 5.79.68.xxx[48661] (40 bytes)
	Mar 15 11:37:14 mainframe charon-custom: 15[NET] received packet: from 5.79.68.xxx[48662] to 10.0.0.2[500] (192 bytes)
	Mar 15 11:37:14 mainframe charon-custom: 15[ENC] parsed ID_PROT request 0 [ SA ]
	Mar 15 11:37:14 mainframe charon-custom: 15[IKE] no IKE config found for 10.0.0.2...5.79.68.xxx, sending NO_PROPOSAL_CHOSEN
	Mar 15 11:37:14 mainframe charon-custom: 15[ENC] generating INFORMATIONAL_V1 request 1077021290 [ N(NO_PROP) ]
	Mar 15 11:37:14 mainframe charon-custom: 15[NET] sending packet: from 10.0.0.2[500] to 5.79.68.xxx[48662] (40 bytes)

**Comment by maciekish** [comment]
That other 5.79.68.xxx ip was somewhere in netherlands so i blocked it in my firewall for now as it looked very strange and kept coming up even though i stopped trying to connect to my VPN. The log looks like this now:

	Mar 15 11:54:16 mainframe charon-custom: 05[NET] received packet: from 94.254.226.xxx[6727] to 10.0.0.2[500] (308 bytes)
	Mar 15 11:54:16 mainframe charon-custom: 05[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(REDIR_SUP) N(NATD_S_IP) N(NATD_D_IP) N(FRAG        _SUP) ]
	Mar 15 11:54:16 mainframe charon-custom: 05[IKE] 94.254.226.xxx is initiating an IKE_SA
	Mar 15 11:54:16 mainframe charon-custom: 05[IKE] local host is behind NAT, sending keep alives
	Mar 15 11:54:16 mainframe charon-custom: 05[IKE] remote host is behind NAT
	Mar 15 11:54:16 mainframe charon-custom: 05[ENC] generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(        MULT_AUTH) ]
	Mar 15 11:54:16 mainframe charon-custom: 05[NET] sending packet: from 10.0.0.2[500] to 94.254.226.xxx[6727] (316 bytes)
	Mar 15 11:54:36 mainframe charon-custom: 06[IKE] sending keep alive to 94.254.226.xxx[6727]
	Mar 15 11:54:46 mainframe charon-custom: 08[JOB] deleting half open IKE_SA after timeout

**Comment by maciekish** [comment]
Seems to start up and find cert fine. I heard iOS is sensitive about the cert but the CN is the same in all places as well as remote id on client.

	● strongswan.service - strongSwan IPsec services
	   Loaded: loaded (/lib/systemd/system/strongswan.service; enabled; vendor preset: enabled)
	   Active: active (running) since Wed 2017-03-15 12:13:01 CET; 865ms ago
	  Process: 9391 ExecStopPost=/bin/rm -f /var/run/charon.pid /var/run/starter.charon.pid (code=exited, status=0/SUCCESS)
	  Process: 9382 ExecStop=/usr/sbin/ipsec stop (code=exited, status=0/SUCCESS)
	  Process: 9398 ExecStart=/usr/sbin/ipsec start (code=exited, status=0/SUCCESS)
	  Process: 9394 ExecStartPre=/bin/mkdir -p /var/lock/subsys (code=exited, status=0/SUCCESS)
	 Main PID: 9414 (starter)
	    Tasks: 18 (limit: 4915)
	   CGroup: /system.slice/strongswan.service
	           ├─9414 /usr/lib/ipsec/starter --daemon charon
	           └─9415 /usr/lib/ipsec/charon --use-syslog

	Mar 15 12:13:01 mainframe charon-custom[9415]: 00[CFG] opening triplet file /etc/ipsec.d/triplets.dat failed: No such file or directory
	Mar 15 12:13:01 mainframe charon-custom[9415]: 00[CFG] loaded 0 RADIUS server configurations
	Mar 15 12:13:01 mainframe charon-custom[9415]: 00[LIB] loaded plugins: charon test-vectors aes rc2 sha1 sha2 md4 md5 random nonce x509 revocat
	Mar 15 12:13:01 mainframe charon-custom[9415]: 00[LIB] dropped capabilities, running as uid 0, gid 0
	Mar 15 12:13:01 mainframe charon-custom[9415]: 00[JOB] spawning 16 worker threads
	Mar 15 12:13:01 mainframe ipsec_starter[9414]: charon (9415) started after 60 ms
	Mar 15 12:13:01 mainframe charon-custom[9415]: 09[CFG] received stroke: add connection 'roadwarrior'
	Mar 15 12:13:01 mainframe charon-custom[9415]: 09[CFG] adding virtual IP address pool 10.0.0.0/22
	Mar 15 12:13:01 mainframe charon-custom[9415]: 09[CFG]   loaded certificate "CN=***.****.name" from 'cert.pem'
	Mar 15 12:13:01 mainframe charon-custom[9415]: 09[CFG] added configuration 'roadwarrior'

**Comment by maciekish** [comment]
On the iPhone side i can see it doing a DNS lookup and attempting to connect, then failing with `Failed to receive IKE Auth Package` after a while.

**Comment by jawj** [comment]
Just to check, you're configuring the iOS client using the profile generated by the script?

I wonder if there's any issue with your server being behind NAT, but I'm afraid I'm no StrongSwan expert — maybe try one of the StrongSwan support options here: https://www.strongswan.org/support.html

**Comment by maciekish** [comment]
Yes, i tried both the `.mobileconfig` and entering it manually.

**Comment by maciekish** [comment]
Docs say NAT should be handled automagically :( https://wiki.strongswan.org/projects/strongswan/wiki/NatTraversal
