### ISSUE TITLE
Error : No such network interface : Public IP

### ISSUE THREAD

**Issue by EnthusiastKE** [jawj/IKEv2-setup#82]
Dear Team,

Might be a newbie question. I am having this error when running the script. **No such network interface : 185.6....**
I am running this on a Ubuntu 18.04 hosted on a virtual cloud (VPS) server.
--- Configuration: VPN settings ---

No such network interface: 185.135.*.**

---------------------Part of LOG ---
Feb 10 17:06:21 f09hd6s7qm systemd[1]: Created slice system-postfix.slice.
Feb 10 17:06:21 f09hd6s7qm systemd[1]: Starting Postfix Mail Transport Agent (instance -)...
Feb 10 17:06:21 f09hd6s7qm configure-instance.sh[10700]: postconf: fatal: open /etc/postfix/main.cf: No such file or directory
Feb 10 17:06:22 f09hd6s7qm configure-instance.sh[10700]: postconf: fatal: open /etc/postfix/main.cf: No such file or directory
Feb 10 17:06:23 f09hd6s7qm systemd[1]: postfix@-.service: Control process exited, code=exited status=1
Feb 10 17:06:23 f09hd6s7qm systemd[1]: postfix@-.service: Failed with result 'exit-code'.
Feb 10 17:06:23 f09hd6s7qm systemd[1]: Failed to start Postfix Mail Transport Agent (instance -).
Feb 10 17:06:30 f09hd6s7qm systemd[1]: Reloading.
Feb 10 17:06:30 f09hd6s7qm systemd[1]: /lib/systemd/system/vzfifo.service:19: Support for option SysVStartPriority= has been removed and it is ignored
Feb 10 17:06:30 f09hd6s7qm systemd[1]: Starting Postfix Mail Transport Agent (instance -)...
Feb 10 17:06:31 f09hd6s7qm postfix/postfix-script[11038]: starting the Postfix mail system
Feb 10 17:06:31 f09hd6s7qm postfix/master[11040]: daemon started -- version 3.3.0, configuration /etc/postfix
Feb 10 17:06:31 f09hd6s7qm systemd[1]: Started Postfix Mail Transport Agent (instance -).
Feb 10 17:06:31 f09hd6s7qm systemd[1]: Starting Postfix Mail Transport Agent...
Feb 10 17:06:33 f09hd6s7qm systemd[1]: /lib/systemd/system/vzfifo.service:19: Support for option SysVStartPriority= has been removed and it is ignored
Feb 10 17:06:34 f09hd6s7qm systemd[1]: Reloading.
Feb 10 17:06:34 f09hd6s7qm systemd[1]: /lib/systemd/system/vzfifo.service:19: Support for option SysVStartPriority= has been removed and it is ignored
Feb 10 17:06:34 f09hd6s7qm systemd[1]: Reloading.
Feb 10 17:06:34 f09hd6s7qm systemd[1]: /lib/systemd/system/vzfifo.service:19: Support for option SysVStartPriority= has been removed and it is ignored
Feb 10 17:06:34 f09hd6s7qm systemd[1]: Started strongSwan IPsec IKEv1/IKEv2 daemon using ipsec.conf.
Feb 10 17:06:34 f09hd6s7qm ipsec[11186]: Starting strongSwan 5.6.2 IPsec [starter]...
Feb 10 17:06:34 f09hd6s7qm ipsec[11186]: no netkey IPsec stack detected
Feb 10 17:06:34 f09hd6s7qm ipsec[11186]: no KLIPS IPsec stack detected
Feb 10 17:06:34 f09hd6s7qm ipsec[11186]: no known IPsec stack detected, ignoring!
Feb 10 17:06:34 f09hd6s7qm charon: 00[DMN] Starting IKE charon daemon (strongSwan 5.6.2, Linux 4.15.0, x86_64)
Feb 10 17:06:34 f09hd6s7qm charon: 00[CFG] loading ca certificates from '/etc/ipsec.d/cacerts'
Feb 10 17:06:34 f09hd6s7qm charon: 00[CFG] loading aa certificates from '/etc/ipsec.d/aacerts'
Feb 10 17:06:34 f09hd6s7qm charon: 00[CFG] loading ocsp signer certificates from '/etc/ipsec.d/ocspcerts'
Feb 10 17:06:34 f09hd6s7qm charon: 00[CFG] loading attribute certificates from '/etc/ipsec.d/acerts'
Feb 10 17:06:34 f09hd6s7qm charon: 00[CFG] loading crls from '/etc/ipsec.d/crls'
Feb 10 17:06:34 f09hd6s7qm charon: 00[CFG] loading secrets from '/etc/ipsec.secrets'
Feb 10 17:06:34 f09hd6s7qm charon: 00[LIB] loaded plugins: charon aesni aes rc2 sha2 sha1 md4 md5 mgf1 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem openssl fips-prf gmp agent xcbc hmac gcm attr kernel-netlink resolve socket-default connmark stroke updown eap-mschapv2 xauth-generic counters
Feb 10 17:06:34 f09hd6s7qm charon: 00[LIB] dropped capabilities, running as uid 0, gid 0
Feb 10 17:06:34 f09hd6s7qm charon: 00[JOB] spawning 16 worker threads
Feb 10 17:06:34 f09hd6s7qm ipsec[11186]: charon (11197) started after 20 ms
Feb 10 17:06:40 f09hd6s7qm systemd[1]: Reloading.
Feb 10 17:06:40 f09hd6s7qm systemd[1]: /lib/systemd/system/vzfifo.service:19: Support for option SysVStartPriority= has been removed and it is ignored
Feb 10 17:06:40 f09hd6s7qm systemd[1]: Reloading.
Feb 10 17:06:40 f09hd6s7qm systemd[1]: /lib/systemd/system/vzfifo.service:19: Support for option SysVStartPriority= has been removed and it is ignored
Feb 10 17:06:40 f09hd6s7qm systemd[1]: Reloading.
Feb 10 17:06:40 f09hd6s7qm systemd[1]: /lib/systemd/system/vzfifo.service:19: Support for option SysVStartPriority= has been removed and it is ignored
Feb 10 17:06:41 f09hd6s7qm systemd[1]: Started Run certbot twice daily.
Feb 10 17:07:03 f09hd6s7qm systemd[1]: Reloading.
Feb 10 17:07:03 f09hd6s7qm systemd[1]: /lib/systemd/system/vzfifo.service:19: Support for option SysVStartPriority= has been removed and it is ignored

Please assist.

Thanks

**Comment by thehiccupproject** [comment]
Oh dear — evidently we've reached Let's Encrypt's [rate limit](https://letsencrypt.org/docs/rate-limits/) for the sslip.io domain. I probably need to remove this as the default domain setup.

**Comment by jawj** [comment]
Hmm. This looks similar to #92. If you could post the output of `ip route get 1.1.1.1` it would be helpful. Thanks.
