### ISSUE TITLE
Error creating new cert :: too many certificates already

### ISSUE THREAD

**Issue by EnthusiastKE** [jawj/IKEv2-setup#83]
Hello All,
I keep getting this error when running the installation script. At the last steps. Please assist.

--- Configuring RSA certificates ---

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Running pre-hook command: /sbin/iptables -I INPUT -p tcp --dport 80 -j ACCEPT
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for 102.129.***.***.sslip.io
Waiting for verification...
Cleaning up challenges
Running post-hook command: /sbin/iptables -D INPUT -p tcp --dport 80 -j ACCEPT
An unexpected error occurred:
There were too many requests of a given type :: Error creating new cert :: too many certificates already issued for: sslip.io: see https://letsencrypt.org/docs/rate-limits/
Please see the logfiles in /var/log/letsencrypt for more details.

**Comment by jawj** [comment]
Oh dear — evidently we've reached Let's Encrypt's [rate limit](https://letsencrypt.org/docs/rate-limits/) for the sslip.io domain. I probably need to remove this as the default domain setup.

**Comment by carusyte** [comment]
I switched to xip.io as a workaround

**Comment by jawj** [comment]
Great. I've now stopped defaulting to sslip.io for this reason.
