### ISSUE TITLE
Policy match error on Windows 10

### ISSUE THREAD

**Issue by AtomicLemon** [jawj/IKEv2-setup#84]
Hello!

I am getting a policy match error on Windows 10...
Screenshot:
![capture1](https://user-images.githubusercontent.com/46167928/53998696-86e3dc00-41a5-11e9-80c7-6fc570d2a020.JPG)

Is there anyway I can get past this? I think it is a encryption issue, but I have no idea.

Any help is appreciated!

EDIT: I forgot to add that I used the ed25519 option.

**Comment by jawj** [comment]
Can you check the [Troubleshooting section of the README](https://github.com/jawj/IKEv2-setup#troubleshooting) and post any relevant logs?

**Comment by AtomicLemon** [comment]
I dont know where to find the Windows logs, but I can post the server logs.

```
Mar  9 06:33:04 Babee charon: 14[NET] received packet: from 103.237.164.6[18168] to 45.32.243.173[500] (376 bytes)
Mar  9 06:33:04 Babee charon: 14[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) V V V V ]
Mar  9 06:33:04 Babee charon: 14[IKE] received MS NT5 ISAKMPOAKLEY v9 vendor ID
Mar  9 06:33:04 Babee charon: 14[IKE] received MS-Negotiation Discovery Capable vendor ID
Mar  9 06:33:04 Babee charon: 14[IKE] received Vid-Initial-Contact vendor ID
Mar  9 06:33:04 Babee charon: 14[ENC] received unknown vendor ID: 01:52:8b:bb:c0:06:96:12:18:49:ab:9a:1c:5b:2a:51:00:00:00:02
Mar  9 06:33:04 Babee charon: 14[IKE] 103.237.164.6 is initiating an IKE_SA
Mar  9 06:33:04 Babee charon: 14[IKE] remote host is behind NAT
Mar  9 06:33:04 Babee charon: 14[ENC] generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(MULT_AUTH) ]
Mar  9 06:33:04 Babee charon: 14[NET] sending packet: from 45.32.243.173[500] to 103.237.164.6[18168] (272 bytes)
```

**Comment by AtomicLemon** [comment]
Maybe something to do with this? https://www.stevenjordan.net/2016/09/secure-ikev2-win-10.html

**Comment by AtomicLemon** [comment]
I found that on another Windows 10 device, it works fine, and the registry values are the same in that folder

**Comment by AtomicLemon** [comment]
An Upgrade to the latest version of Windows fixes this.
