### ISSUE TITLE
Root User lost after a few days

### ISSUE THREAD

**Issue by 1d0navan** [jawj/IKEv2-setup#85]
Hello,

i don't know if im alone with this problem, but if i set up my server with this script my root account is inaccessable after a few days. So im reinstalling it, creating a new pw and so on. But the problem still exists then. after a few days i cant access it anymore.

**Comment by jawj** [comment]
The script changes settings so as to disable root login and create a new login user who is a sudoer. Does that explain your problem?

**Comment by 1d0navan** [comment]
a few hours later i found it out. but thanks for the explanation! Very well done job man :)
