### ISSUE TITLE
Unable to SSH in from external IP

### ISSUE THREAD

**Issue by gap579137** [jawj/IKEv2-setup#88]
After install and setup everything is working. I am able to connect to the server remotely via ssh on port 22. After reboot tho I am no longer able to connect to SSH remotely via port 22.

During setup the following options are selected:
Server domain - xyz.123.com (example)
SSH Port - 22
Any help would be greatly appreciated!

TIA

**Comment by EnthusiastKE** [comment]
Please paste your configuration settings (Ipsec.conf) to assist in the
troubleshooting.

**Comment by jawj** [comment]
In what way are you unable to connect? The script disables root user login in favour of the user account it sets up.

**Comment by gap579137** [comment]
Well, I wiped that VPS and started fresh and now I am able to get everything working. Not sure what happened the first time. Now to just figure out how to get netdata working.
