### ISSUE TITLE
How to change hostname?

### ISSUE THREAD

**Issue by bibendi** [jawj/IKEv2-setup#89]
Hey! 

First of all, I want to say thank you for this neat script!

Is there any workaround to change the hostname of a VPN server?
Can I just rerun this script, where I'll provide the new hostname, or I need to create a brand new virtual machine?

**Comment by jawj** [comment]
I assume that by hostname you mean public DNS address, such as my.vpn.net? (This is the possibly confusing terminology used in the script).

I think it should work to rerun the script, but if it fails, let me know how.
