### ISSUE TITLE
handling user

### ISSUE THREAD

**Issue by ssageghi** [jawj/IKEv2-setup#90]
Hi!
I used your script to create a vpn server and it's working fine.
my question is how many users can connect together?
some of my friends can't connect and I think it's because of lack of resources.
is there a limitation for connected devices?
thanks!

**Comment by jawj** [comment]
Hi there. I think now it is effectively unlimited (65,536), but of course in practice limited by bandwidth and CPU, and maybe memory too. Inability to connect is perhaps more likely a config issue on their end?
