### ISSUE TITLE
the connection is lost after a few minutes of inactivity in sleep mode on the iphone

### ISSUE THREAD

**Issue by ddi98** [jawj/IKEv2-setup#91]
hi, everything works great, but when I'm connected on the VPN from the iphone, after a few minutes, sometimes even after an hour in sleep mode the connection falls, is there any parameter I can change to prevent this from happening? thank you so much

**Comment by jawj** [comment]
I use this setup in my iPhone and have not seen this. Have you checked the client and server logs as suggested in the README?
