### ISSUE TITLE
Problem binding to port 80: Could not bind to IPv4 or IPv6

### ISSUE THREAD

**Issue by JerryBian** [jawj/IKEv2-setup#95]
While run the setup script, it shows failure, can you explain or guide how to fix this issue?

```
--- Configuring RSA certificates ---

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Running pre-hook command: /sbin/iptables -I INPUT -p tcp --dport 80 -j ACCEPT
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for vpn.xxx.xx
Cleaning up challenges
Running post-hook command: /sbin/iptables -D INPUT -p tcp --dport 80 -j ACCEPT
Problem binding to port 80: Could not bind to IPv4 or IPv6.
```

**Comment by as1414** [comment]
same

**Comment by as1414** [comment]
Looks like this helped me get through this error...

Apache is already installed and running on the machine: https://community.letsencrypt.org/t/problem-binding-to-port-80-could-not-bind-to-ipv4-or-ipv6/77033/7

First, double check like this: https://www.tecmint.com/check-apache-httpd-status-and-uptime-in-linux/

Remove if needed: http://xmodulo.com/how-to-uninstall-and-remove-apache2-on-ubuntu-debian.html

Re-run the script - this worked for me.  I'm not a Linux/Ubuntu expert so please excuse the lack of information in this comment/answer

**Comment by jawj** [comment]
Right, this script expects a freshly installed Ubuntu with no extra services running, including nothing bound to port 80. @as1414's advice looks good to me.
