### ISSUE TITLE
the iptables rules makes my nginx response with nothing

### ISSUE THREAD

**Issue by sooxiaotong** [jawj/IKEv2-setup#99]
I flushed all my iptables and it works again with ufw

**Comment by jawj** [comment]
Well the iptables rules are designed for a box doing nothing else, as is mentioned in the README.

**Comment by dmitry-kostin** [comment]
Just bumped into such issue; share solution for others, you need to disable drop all packets rule
```iptables -D INPUT -j DROP```
or I suspect explicitly allow 80, 443 traffic
